export const mockOrdersList = [
  {
   "order_date": "17-сен-2023",
   "gos_number": "а511на 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Геликон",
   "work_summary": "5+1",
   "work_time_start": "12:30",
   "address_start": "Геликон - Зарядье - Крокус",
   "work_time_end": "15:00",
   "order_cost": 5600,
   "work_in_hours": 6,
   "extra_time": 2,
   "rate_per_hour": 933.29,
   "mkad_over_distance": 77,
   "rate_per_km": 30,
   "extra_money": 2000,
   "comments": "comment"
  },
  {
   "order_date": "17-сен-2023",
   "gos_number": "а511на 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Геликон",
   "work_summary": "5+1",
   "work_time_start": "20:00",
   "address_start": "Крокус",
   "address_end": "Геликон",
   "work_time_end": "21:00",
   "order_cost": 5600,
   "work_in_hours": 6,
   "rate_per_hour": 933.29
  },
  {
   "order_date": "17-сен-2023",
   "gos_number": 707,
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Мейерхольда",
   "work_summary": 2500,
   "work_time_start": "15:00",
   "address_start": "ЦиМ",
   "address_end": "Энтузиастов",
   "work_time_end": "17:00",
   "order_cost": 4578,
   "work_in_hours": 6,
   "rate_per_hour": 762.95
  },
  {
   "order_date": "17-сен-2023",
   "gos_number": "о908ор 197",
   "disp_name": "Андрей",
   "client_name": "Нэкст",
   "work_summary": "7,5+1+70км",
   "work_time_start": "08:00",
   "address_start": "Каширский пр.",
   "address_end": "Радумля",
   "work_time_end": "15:30",
   "order_cost": 8550,
   "work_in_hours": 8.5,
   "rate_per_hour": 800,
   "mkad_over_distance": 70,
   "rate_per_km": 25
  },
  {
   "order_date": "17-сен-2023",
   "gos_number": "о908ор 197",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Геликон",
   "work_summary": "6+1",
   "work_time_start": "21:00",
   "address_start": "Зарядье",
   "work_time_end": "23:30",
   "order_cost": 7280,
   "work_in_hours": 7,
   "rate_per_hour": 1040
  },
  {
   "order_date": "16-сен-2023",
   "gos_number": "м601рр 197",
   "disp_name": "Андрей",
   "client_name": "Нэкст",
   "work_summary": "6+1+130км",
   "work_time_start": "09:00",
   "address_start": "Каширский пр.",
   "address_end": "Атепцево",
   "work_time_end": "14:00",
   "order_cost": 8850,
   "work_in_hours": 7,
   "rate_per_hour": 800,
   "mkad_over_distance": 130,
   "rate_per_km": 25
  },
  {
   "order_date": "16-сен-2023",
   "gos_number": "м601рр 197",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Геликон",
   "work_summary": "6+1",
   "work_time_start": "21:00",
   "address_start": "Зарядье",
   "work_time_end": "23:30",
   "order_cost": 7280,
   "work_in_hours": 7,
   "rate_per_hour": 1040
  },
  {
   "order_date": "16-сен-2023",
   "gos_number": "в313ае 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Вахтангова",
   "work_summary": "7+1",
   "work_time_start": "09:00",
   "work_time_end": "14:00",
   "order_cost": 7000,
   "work_in_hours": 8,
   "rate_per_hour": 875
  },
  {
   "order_date": "16-сен-2023",
   "gos_number": "к562ер 799",
   "disp_name": "ПрестижАвто",
   "client_name": "Курьер Сервис",
   "work_summary": "7,5+1+50км",
   "work_time_start": "09:00",
   "address_start": "Угрешка - Грибки - Новое ш. - Томилино",
   "work_time_end": "16:30",
   "order_cost": 8500,
   "work_in_hours": 8.5,
   "rate_per_hour": 1000,
   "mkad_over_distance": 50
  },
  {
   "order_date": "16-сен-2023",
   "gos_number": "к327ер 799",
   "disp_name": "Лариса",
   "client_name": "Палладиум",
   "work_summary": "8,5+1+60км",
   "work_time_start": "08:00",
   "address_start": "Томилино",
   "address_end": "Новорязанское ш. - Путевой пр - Шолохово - Дмитровское ш",
   "work_time_end": "16:30",
   "order_cost": 13365,
   "work_in_hours": 9.5,
   "extra_time": 2,
   "rate_per_hour": 990,
   "mkad_over_distance": 60,
   "rate_per_km": 33,
   "comments": "эксп, груз, 01- 678,327"
  },
  {
   "order_date": "16-сен-2023",
   "gos_number": "т390ту 777",
   "disp_name": "ПрестижАвто",
   "client_name": "Курьер Сервис",
   "work_summary": "11,5+1+80км",
   "work_time_start": "09:00",
   "address_start": "Угрешка - Михалково - Лешково - Томилино",
   "work_time_end": "20:30",
   "order_cost": 12500,
   "work_in_hours": 12.5,
   "rate_per_hour": 1000,
   "mkad_over_distance": 80
  },
  {
   "order_date": "16-сен-2023",
   "gos_number": "т394ту 777",
   "disp_name": "ПрестижАвто",
   "client_name": "Курьер Сервис",
   "work_summary": "8,5+1+45км",
   "work_time_start": "09:00",
   "address_start": "Угрешка - Грибки - Дмитровское ш - Вешки - Новгородская - Томилино",
   "work_time_end": "17:30",
   "order_cost": 9500,
   "work_in_hours": 9.5,
   "rate_per_hour": 1000,
   "mkad_over_distance": 45
  },
  {
   "order_date": "16-сен-2023",
   "gos_number": "т396ту 777",
   "disp_name": "ПрестижАвто",
   "client_name": "Курьер Сервис",
   "work_summary": "10,5+1+25км",
   "work_time_start": "09:00",
   "address_start": "Угерешка - Красная сосна - Чермянная - Томилино ",
   "work_time_end": "19:30",
   "order_cost": 11500,
   "work_in_hours": 11.5,
   "rate_per_hour": 1000,
   "mkad_over_distance": 25
  },
  {
   "order_date": "16-сен-2023",
   "gos_number": "т411ту 777",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. ЭТ СЭТЕРА",
   "work_summary": "7+1+70км",
   "work_time_start": "11:30",
   "address_start": "Пахра",
   "address_end": "Фролов",
   "work_time_end": "14:30",
   "order_cost": 11877,
   "work_in_hours": 8,
   "rate_per_hour": 1484.68,
   "mkad_over_distance": 70
  },
  {
   "order_date": "16-сен-2023",
   "gos_number": "т202рн 799",
   "disp_name": "Валентина",
   "work_summary": "7+1+120км",
   "work_time_start": "08:00",
   "address_start": "Карсино",
   "address_end": "Варшавское ш",
   "work_time_end": "14:30",
   "order_cost": 11200,
   "work_in_hours": 8,
   "rate_per_hour": 950,
   "mkad_over_distance": 120,
   "rate_per_km": 30
  },
  {
   "order_date": "15-сен-2023",
   "gos_number": "т099рн 799",
   "disp_name": "Алексей (расчет)",
   "order_cost": 69100,
   "comments": "аванс"
  },
  {
   "order_date": "15-сен-2023",
   "gos_number": "т678рн 799",
   "disp_name": "Лариса",
   "client_name": "Палладиум",
   "work_summary": "7,5+1+55км",
   "work_time_start": "08:00",
   "address_start": "Томилино",
   "address_end": "Востряковский - Киевское ш - Новомещерский пр - Красногорск",
   "work_time_end": "15:30",
   "order_cost": 12210,
   "work_in_hours": 8.5,
   "extra_time": 2,
   "rate_per_hour": 990,
   "mkad_over_distance": 55,
   "rate_per_km": 33,
   "comments": "эксп, груз, 01- 678,327"
  },
  {
   "order_date": "15-сен-2023",
   "gos_number": "е249са 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "7+1",
   "work_time_start": "09:00",
   "address_start": "пост",
   "work_time_end": "15:30",
   "order_cost": 11000,
   "work_in_hours": 8,
   "extra_time": 2,
   "rate_per_hour": 1100
  },
  {
   "order_date": "15-сен-2023",
   "gos_number": "т579вн 199",
   "disp_name": "ИП Айрапетов",
   "client_name": "ИП Фролов",
   "work_summary": "7+1",
   "work_time_start": "00:30",
   "address_start": "Мосфильм",
   "address_end": "Крокус",
   "work_time_end": "05:30",
   "order_cost": 6800,
   "work_in_hours": 8,
   "rate_per_hour": 850,
   "comments": "7м., Мероприятие: «Лещенко 01.02.22»"
  },
  {
   "order_date": "15-сен-2023",
   "gos_number": "т428ту 777",
   "client_name": "кл. Раф",
   "work_summary": "7+1",
   "work_time_start": "05:00",
   "address_start": "Образцова",
   "address_end": "2 энтузиастов 5к1",
   "work_time_end": "11:30",
   "order_cost": 8000,
   "work_in_hours": 8,
   "rate_per_hour": 1000,
   "comments": "нал"
  },
  {
   "order_date": "14-сен-2023",
   "gos_number": "т442ту 777",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Фоменко",
   "work_summary": "7+1",
   "work_time_start": "09:00",
   "work_time_end": "11:00",
   "order_cost": 7088,
   "work_in_hours": 8
  },
  {
   "order_date": "14-сен-2023",
   "gos_number": "к849от 777",
   "disp_name": "Андрей",
   "client_name": "Нэкст",
   "work_summary": "11,5+1+90км",
   "work_time_start": "05:00",
   "address_start": "Библиотечный",
   "address_end": "Домодедово",
   "work_time_end": "16:30",
   "order_cost": 14580,
   "work_in_hours": 12.5,
   "extra_time": 1,
   "rate_per_hour": 900,
   "mkad_over_distance": 90,
   "rate_per_km": 27,
   "comments": "эксп, на 099"
  },
  {
   "order_date": "14-сен-2023",
   "gos_number": "к789ер 799",
   "client_name": "кл. Раф",
   "work_summary": "7+1",
   "work_time_start": "05:00",
   "address_start": "Образцова",
   "address_end": "2 энтузиастов 5к1",
   "work_time_end": "09:00",
   "order_cost": 8000,
   "work_in_hours": 8,
   "rate_per_hour": 1000,
   "comments": "нал"
  },
  {
   "order_date": "14-сен-2023",
   "gos_number": "к789ер 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Оперетты",
   "work_summary": "7+1",
   "work_time_start": "12:30",
   "work_time_end": "13:30",
   "order_cost": 10106,
   "work_in_hours": 8,
   "rate_per_hour": 1263.25
  },
  {
   "order_date": "14-сен-2023",
   "gos_number": "к249нр 799",
   "client_name": "кл. Раф",
   "work_summary": "7+1",
   "work_time_start": "05:00",
   "address_start": "Образцова",
   "address_end": "2 энтузиастов 5к1",
   "work_time_end": "08:00",
   "order_cost": 8000,
   "work_in_hours": 8,
   "rate_per_hour": 1000,
   "comments": "нал"
  },
  {
   "order_date": "14-сен-2023",
   "gos_number": "е135кн 77",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "сетка",
   "work_time_start": "09:00",
   "address_start": "Пономарев",
   "address_end": 416,
   "order_cost": 26000,
   "work_in_hours": 20,
   "rate_per_hour": 1300
  },
  {
   "order_date": "14-сен-2023",
   "gos_number": "м464хо 199",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "сетка",
   "work_time_start": "09:00",
   "address_start": "Пономарев",
   "address_end": 65,
   "order_cost": 26000,
   "work_in_hours": 20,
   "rate_per_hour": 1300
  },
  {
   "order_date": "14-сен-2023",
   "gos_number": "м474хо 199",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "40 фт",
   "work_time_start": "13:00",
   "address_start": "КСК",
   "address_end": 8011181,
   "order_cost": 56000,
   "work_in_hours": 40,
   "rate_per_hour": 1400
  },
  {
   "order_date": "14-сен-2023",
   "gos_number": "о639со 777",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "40 фт",
   "work_time_start": "13:00",
   "address_start": "КСК",
   "address_end": 8019174,
   "order_cost": 56000,
   "work_in_hours": 40,
   "rate_per_hour": 1400
  },
  {
   "order_date": "14-сен-2023",
   "gos_number": "в645рн 197",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "сетка",
   "work_time_start": "09:00",
   "address_start": "Пономарев",
   "address_end": 280,
   "order_cost": 26000,
   "work_in_hours": 20,
   "rate_per_hour": 1300
  },
  {
   "order_date": "14-сен-2023",
   "gos_number": "в646рн 197",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "сетка",
   "work_time_start": "09:00",
   "address_start": "Пономарев",
   "address_end": 426,
   "order_cost": 26000,
   "work_in_hours": 20,
   "rate_per_hour": 1300
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "в647рн 197",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "40 фт",
   "work_time_start": "13:00",
   "address_start": "КСК",
   "address_end": 8005569,
   "order_cost": 56000,
   "work_in_hours": 40,
   "rate_per_hour": 1400
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "е741уе 77",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "40 фт",
   "work_time_start": "13:00",
   "address_start": "КСК",
   "address_end": 9010127,
   "order_cost": 56000,
   "work_in_hours": 40,
   "rate_per_hour": 1400
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "в152ае 799",
   "disp_name": "Павел",
   "client_name": "Нэкст",
   "work_summary": "10+1+350км",
   "work_time_start": "09:00",
   "address_start": "Талдом",
   "address_end": "Чехов",
   "work_time_end": "19:00",
   "order_cost": 32650,
   "work_in_hours": 11,
   "extra_time": 2,
   "rate_per_hour": 1300,
   "mkad_over_distance": 350,
   "rate_per_km": 45,
   "comments": "2 раст"
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "в262ае 799",
   "disp_name": "Зоя",
   "work_summary": "8+1+108км",
   "work_time_start": "11:00",
   "address_start": "Панино",
   "address_end": "Новорязанское ш",
   "work_time_end": "19:00",
   "order_cost": 0,
   "work_in_hours": 9,
   "mkad_over_distance": 108,
   "extra_money": 350,
   "comments": "01.02 -02.02"
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "т211рн 799",
   "disp_name": "ПрестижАвто",
   "client_name": "Курьер Сервис",
   "work_summary": "7+1+70км",
   "work_time_start": "10:00",
   "address_start": "Томилино - Подольск  Томилино",
   "work_time_end": "16:00",
   "order_cost": 12850,
   "work_in_hours": 8,
   "rate_per_hour": 1300,
   "mkad_over_distance": 70,
   "rate_per_km": 35
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "к818нр 799",
   "disp_name": "ПрестижАвто",
   "client_name": "Курьер Сервис",
   "work_summary": "15+1+104км",
   "work_time_start": "07:00",
   "address_start": "Томилино",
   "address_end": "Белые Столбы",
   "work_time_end": "22:00",
   "order_cost": 24440,
   "work_in_hours": 16,
   "rate_per_hour": 1300,
   "mkad_over_distance": 104,
   "rate_per_km": 35
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "к876нр 799",
   "disp_name": "ПрестижАвто",
   "client_name": "Курьер Сервис",
   "work_summary": "7+1+70км",
   "work_time_start": "10:00",
   "address_start": "Томилино",
   "address_end": "Новосельцево",
   "work_time_end": "14:00",
   "order_cost": 12850,
   "work_in_hours": 8,
   "rate_per_hour": 1300,
   "mkad_over_distance": 70,
   "rate_per_km": 35,
   "comments": "отмена"
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "к895нр 799",
   "disp_name": "Юля Крекшино",
   "work_summary": "7+1+70км",
   "work_time_start": "09:30",
   "address_start": "Дедовск",
   "address_end": "Апрелевка",
   "work_time_end": "16:00",
   "order_cost": 0,
   "work_in_hours": 8,
   "mkad_over_distance": 70
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "т617рн 799",
   "disp_name": "ПрестижАвто",
   "client_name": "Курьер Сервис",
   "work_summary": "7+1+70км",
   "work_time_start": "08:00",
   "address_start": "Томилино",
   "address_end": "Новосельцево",
   "work_time_end": "14:00",
   "order_cost": 12850,
   "work_in_hours": 8,
   "rate_per_hour": 1300,
   "mkad_over_distance": 70,
   "rate_per_km": 35,
   "comments": "отмена"
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "т632рн 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "сетка",
   "work_time_start": "09:00",
   "address_start": "Пономарев",
   "address_end": 332,
   "order_cost": 26000,
   "work_in_hours": 20,
   "rate_per_hour": 1300
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "Ашоту",
   "disp_name": "Соня",
   "order_cost": 15170
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "микроавтобус",
   "disp_name": "Вячеслав",
   "client_name": "т. ЭТ СЭТЕРА",
   "work_summary": 5400,
   "work_time_start": "10:00",
   "address_start": "Фролов - Пахра - Фролов",
   "order_cost": 6480,
   "work_in_hours": 6,
   "rate_per_hour": 1080,
   "mkad_over_distance": 70,
   "comments": "микр 6 чел, 1 07. Фролов 10 00  5400р  х639ос777 "
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "а037тт 92",
   "disp_name": "Лариса",
   "client_name": "Палладиум",
   "order_cost": 12530,
   "work_in_hours": 11,
   "extra_time": 2,
   "rate_per_hour": 770,
   "mkad_over_distance": 105,
   "rate_per_km": 24,
   "comments": "01- а037тт92. Пищугин ЕА. 11+1+эксп*770+105км"
  },
  {
   "order_date": "1-фев-2022",
   "gos_number": "к976ар 190",
   "disp_name": "Лариса",
   "client_name": "Логистические Системы",
   "order_cost": 23000,
   "work_in_hours": 12,
   "rate_per_hour": 1500,
   "mkad_over_distance": 100,
   "rate_per_km": 50,
   "comments": "01- к976ар190. Говорушко ДА. 8+2+2раст*1500+100км.  (1доп час)"
  },
  {
   "order_date": "2-фев-2022",
   "gos_number": "а511на 799",
   "disp_name": "Римма Егоровна",
   "client_name": "т. Виктюка",
   "work_summary": "5+1+70км",
   "work_time_start": "11:00",
   "address_start": "Пахра",
   "address_end": "Стромынка",
   "work_time_end": "15:00",
   "order_cost": 0,
   "work_in_hours": 6,
   "mkad_over_distance": 70,
   "comments": "3м."
  },
  {
   "order_date": "13-сен-2023",
   "gos_number": "а511на 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Геликон",
   "work_summary": "5+1",
   "work_time_start": "15:30",
   "work_time_end": "16:00",
   "order_cost": 5600,
   "work_in_hours": 6,
   "rate_per_hour": 933.29
  },
  {
   "order_date": "13-сен-2023",
   "gos_number": "о908ор 197",
   "disp_name": "Лариса",
   "client_name": "Палладиум",
   "work_summary": "8+1+45км",
   "work_time_start": "08:00",
   "address_start": "Томилино",
   "address_end": "Новрязанка - Дзержинское ш - Красковский - Горьквское ш",
   "work_time_end": "16:00",
   "order_cost": 11030,
   "work_in_hours": 9,
   "extra_time": 2,
   "rate_per_hour": 880,
   "mkad_over_distance": 45,
   "rate_per_km": 30,
   "comments": "эксп, груз, 02- 327,908"
  },
  {
   "order_date": "13-сен-2023",
   "gos_number": "м601рр 197",
   "disp_name": "Андрей",
   "client_name": "Нэкст",
   "work_summary": "8+1+78км",
   "work_time_start": "08:00",
   "address_start": "Библиотечный",
   "address_end": "Реутов",
   "work_time_end": "16:00",
   "order_cost": 9950,
   "work_in_hours": 9,
   "extra_time": 1,
   "rate_per_hour": 800,
   "mkad_over_distance": 78,
   "rate_per_km": 25,
   "comments": "5м, эксп"
  },
  {
   "order_date": "13-сен-2023",
   "gos_number": "у682кт 799",
   "disp_name": "Римма Егоровна",
   "client_name": "т. Виктюка",
   "work_summary": "7+1",
   "work_time_start": "10:00",
   "address_start": "Стромынка",
   "work_time_end": "15:00",
   "order_cost": 6800,
   "work_in_hours": 8,
   "rate_per_hour": 850
  },
  {
   "order_date": "13-сен-2023",
   "gos_number": "в313ае 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Оперетты",
   "work_summary": "7+1",
   "work_time_start": "09:00",
   "address_start": "Каланчевская - Оперетта - Каланчевская",
   "work_time_end": "11:00",
   "order_cost": 10106,
   "work_in_hours": 8,
   "rate_per_hour": 1263.25
  },
  {
   "order_date": "12-сен-2023",
   "gos_number": "в313ае 799",
   "disp_name": "ПрестижАвто",
   "client_name": "Курьер Сервис",
   "work_summary": "7,5+1+60км",
   "work_time_start": "12:00",
   "address_start": "Угрешка - Новомилетское ш - Томилино",
   "work_time_end": "19:30",
   "order_cost": 8500,
   "work_in_hours": 8.5,
   "rate_per_hour": 1000,
   "mkad_over_distance": 60
  },
  {
   "order_date": "12-сен-2023",
   "gos_number": "к562ер 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Оперетты",
   "work_summary": "7+1",
   "work_time_start": "09:00",
   "address_start": "Каланчевская - Оперетта - Каланчевская",
   "work_time_end": "11:00",
   "order_cost": 10106,
   "work_in_hours": 8,
   "rate_per_hour": 1263.25
  },
  {
   "order_date": "12-сен-2023",
   "gos_number": "к562ер 799",
   "disp_name": "ПрестижАвто",
   "client_name": "Курьер Сервис",
   "work_summary": "15,5+1+15км",
   "work_time_start": "12:00",
   "address_start": "Угрешка",
   "address_end": "Химки ",
   "work_time_end": "03:30",
   "order_cost": 16500,
   "work_in_hours": 16.5,
   "rate_per_hour": 1000,
   "mkad_over_distance": 15
  },
  {
   "order_date": "11-сен-2023",
   "gos_number": "к327ер 799",
   "disp_name": "Лариса",
   "client_name": "Палладиум",
   "work_summary": "11+1+190км",
   "work_time_start": "08:00",
   "address_start": "Томилино",
   "address_end": "Алтуфьево - Дмитровское ш. - Глазово - Борозда - Ржавки",
   "work_time_end": "19:00",
   "order_cost": 20130,
   "work_in_hours": 12,
   "extra_time": 2,
   "rate_per_hour": 990,
   "mkad_over_distance": 190,
   "rate_per_km": 33,
   "comments": "эксп, груз, 02- 327,908"
  },
  {
   "order_date": "11-сен-2023",
   "gos_number": "т390ту 777",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Новая опера",
   "work_summary": "7+1+70км",
   "work_time_start": "10:30",
   "work_time_end": "15:30",
   "order_cost": 7095,
   "work_in_hours": 8,
   "rate_per_hour": 886.87,
   "mkad_over_distance": 70
  },
  {
   "order_date": "11-сен-2023",
   "gos_number": "т394ту 777",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. на М. Бронной",
   "work_summary": "7+1+70км",
   "work_time_start": "09:00",
   "address_start": "Журавлева",
   "address_end": "Пахра",
   "work_time_end": "13:30",
   "order_cost": 10500,
   "work_in_hours": 8,
   "extra_time": 2.5,
   "rate_per_hour": 1000,
   "mkad_over_distance": 70
  },
  {
   "order_date": "11-сен-2023",
   "gos_number": "т396ту 777",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Маяковского",
   "work_summary": "7+1+70км",
   "work_time_start": "09:00",
   "work_time_end": "14:30",
   "order_cost": 9700,
   "work_in_hours": 8,
   "rate_per_hour": 950,
   "mkad_over_distance": 70,
   "rate_per_km": 30
  },
  {
   "order_date": "10-сен-2023",
   "gos_number": "т411ту 777",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. на М. Бронной",
   "work_summary": "7+1+70км",
   "work_time_start": "09:00",
   "address_start": "Журавлева",
   "address_end": "Пахра",
   "work_time_end": "13:30",
   "order_cost": 10500,
   "work_in_hours": 8,
   "extra_time": 2.5,
   "rate_per_hour": 1000,
   "mkad_over_distance": 70
  },
  {
   "order_date": "18-сен-2023",
   "gos_number": "т202рн 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Новая опера",
   "work_summary": "7+1+70км",
   "work_time_start": "11:00",
   "work_time_end": "16:00",
   "order_cost": 7095,
   "work_in_hours": 8,
   "rate_per_hour": 886.87,
   "mkad_over_distance": 70
  },
  {
   "order_date": "18-сен-2023",
   "gos_number": "т678рн 799",
   "disp_name": "ПрестижАвто",
   "client_name": "Курьер Сервис",
   "work_summary": "9,5+1+200км",
   "work_time_start": "09:00",
   "address_start": "Угрешка - Ярославское ш - Сергиев Посад - Угрешка",
   "work_time_end": "18:30",
   "order_cost": 10500,
   "work_in_hours": 10.5,
   "rate_per_hour": 1000,
   "mkad_over_distance": 200
  },
  {
   "order_date": "19-сен-2023",
   "gos_number": "е249са 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "7+1",
   "work_time_start": "09:00",
   "address_start": "пост",
   "work_time_end": "13:00",
   "order_cost": 11000,
   "work_in_hours": 8,
   "extra_time": 2,
   "rate_per_hour": 1100
  },
  {
   "order_date": "19-сен-2023",
   "gos_number": "т579вн 199",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Новая опера",
   "work_summary": "7,5+1+70км",
   "work_time_start": "09:30",
   "work_time_end": "17:00",
   "order_cost": 7538,
   "work_in_hours": 8.5,
   "rate_per_hour": 886.87,
   "mkad_over_distance": 70
  },
  {
   "order_date": "19-сен-2023",
   "gos_number": "т428ту 777",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Новая опера",
   "work_summary": "7+1+70км",
   "work_time_start": "09:00",
   "work_time_end": "15:00",
   "order_cost": 7095,
   "work_in_hours": 8,
   "rate_per_hour": 886.87,
   "mkad_over_distance": 70
  },
  {
   "order_date": "19-сен-2023",
   "gos_number": "т442ту 777",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Фоменко",
   "work_summary": "7+1+110км",
   "work_time_start": "09:00",
   "work_time_end": "13:00",
   "order_cost": 7088,
   "work_in_hours": 8,
   "mkad_over_distance": 110
  },
  {
   "order_date": "20-сен-2023",
   "gos_number": "к849от 777",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Оперетты",
   "work_summary": "7+1",
   "work_time_start": "09:00",
   "address_start": "Каланчевская - Оперетта - Каланчевская",
   "work_time_end": "11:00",
   "order_cost": 10106,
   "work_in_hours": 8,
   "rate_per_hour": 1263.25
  },
  {
   "order_date": "20-сен-2023",
   "gos_number": "к849от 777",
   "disp_name": "Римма",
   "work_summary": "7+1+20км",
   "work_time_start": "14:00",
   "address_start": "Балашиха",
   "address_end": "Дубнинская",
   "work_time_end": "16:30",
   "order_cost": 0,
   "work_in_hours": 8,
   "mkad_over_distance": 20,
   "comments": "на 099"
  },
  {
   "order_date": "20-сен-2023",
   "gos_number": "к816ер 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "7+1",
   "work_time_start": "09:00",
   "address_start": "Пономарев",
   "work_time_end": "13:30",
   "order_cost": 11500,
   "work_in_hours": 8,
   "extra_time": 2,
   "rate_per_hour": 1150
  },
  {
   "order_date": "20-сен-2023",
   "gos_number": "к789ер 799",
   "client_name": "кл. Раф",
   "work_summary": "7+1",
   "work_time_start": "05:00",
   "address_start": "Образцова",
   "address_end": "2 энтузиастов 5к1",
   "work_time_end": "08:00",
   "order_cost": 8000,
   "work_in_hours": 8,
   "rate_per_hour": 1000,
   "comments": "нал"
  },
  {
   "order_date": "20-сен-2023",
   "gos_number": "к789ер 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Новая опера",
   "work_summary": "7+1+70км",
   "work_time_start": "10:00",
   "work_time_end": "15:00",
   "order_cost": 7095,
   "work_in_hours": 8,
   "rate_per_hour": 886.87,
   "mkad_over_distance": 70
  },
  {
   "order_date": "20-сен-2023",
   "gos_number": "к249нр 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Новая опера",
   "work_summary": "8+1+70км",
   "work_time_start": "08:30",
   "work_time_end": "16:30",
   "order_cost": 7982,
   "work_in_hours": 9,
   "rate_per_hour": 886.87,
   "mkad_over_distance": 70
  },
  {
   "order_date": "21-сен-2023",
   "gos_number": "н403ок 799",
   "disp_name": "ИП Айрапетов",
   "client_name": "т. Новая опера",
   "work_summary": "7+1+70км",
   "work_time_start": "08:00",
   "work_time_end": "15:00",
   "order_cost": 7095,
   "work_in_hours": 8,
   "rate_per_hour": 886.87,
   "mkad_over_distance": 70
  },
  {
   "order_date": "21-сен-2023",
   "gos_number": "е135кн 77",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "сетка",
   "work_time_start": "09:00",
   "address_start": "Пономарев",
   "address_end": 133,
   "order_cost": 26000,
   "work_in_hours": 20,
   "rate_per_hour": 1300
  },
  {
   "order_date": "21-сен-2023",
   "gos_number": "м464хо 199",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "сетка",
   "work_time_start": "09:00",
   "address_start": "Пономарев",
   "address_end": 343,
   "order_cost": 26000,
   "work_in_hours": 20,
   "rate_per_hour": 1300
  },
  {
   "order_date": "21-сен-2023",
   "gos_number": "м474хо 199",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "40 фт",
   "work_time_start": "13:00",
   "address_start": "КСК",
   "address_end": 9009971,
   "order_cost": 56000,
   "work_in_hours": 40,
   "rate_per_hour": 1400
  },
  {
   "order_date": "22-сен-2023",
   "gos_number": "в645рн 197",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "сетка",
   "work_time_start": "09:00",
   "address_start": "Пономарев",
   "address_end": 381,
   "order_cost": 26000,
   "work_in_hours": 20,
   "rate_per_hour": 1300
  },
  {
   "order_date": "22-сен-2023",
   "gos_number": "в646рн 197",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "сетка",
   "work_time_start": "09:00",
   "address_start": "Пономарев",
   "address_end": 262,
   "order_cost": 26000,
   "work_in_hours": 20,
   "rate_per_hour": 1300
  },
  {
   "order_date": "23-сен-2023",
   "gos_number": "в647рн 197",
   "disp_name": "ИП Айрапетов",
   "client_name": "БТ",
   "work_summary": "40 фт",
   "work_time_start": "13:00",
   "address_start": "КСК",
   "address_end": 8017314,
   "order_cost": 56000,
   "work_in_hours": 40,
   "rate_per_hour": 1400
  }
 ]