export const mock_car = [
  {
   "gos_number": "а230на 799",
   "marka": "Ford Tranzit",
   "load_capacity": 2,
   "inner_length": 4.22,
   "inner_width": 2.08,
   "inner_height": 2.07,
   "gate_height": 2.02,
   "gate_width": 2.02,
   "cargo_volume": 18.2,
   "outer_auto_dimensions": "6.85 x 2.21 x 3.04",
   "pallets_or_trailer": "8 пал.\n(5+3)",
   "tires": "матадор 195x75x16",
   "group_name": "4м",
   "is_service": "false",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "а511на 799",
   "marka": "Ford Tranzit",
   "load_capacity": 2,
   "inner_length": 4.22,
   "inner_width": 2.08,
   "inner_height": 2.07,
   "gate_height": 2.02,
   "gate_width": 2.02,
   "cargo_volume": 18.2,
   "outer_auto_dimensions": "6.85 x 2.21 x 3.04 выс - 0,88 м",
   "pallets_or_trailer": "8 пал.\n(5+3)",
   "tires": "корморан 195x75x16",
   "fixed_driver": "Ткачук Александр Сергеевич",
   "group_name": "4м",
   "is_service": "false",
   "is_driver_exist": "true",
   "work_status": "work",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "о908ор 197",
   "marka": "Hyundai HD72",
   "load_capacity": 4,
   "inner_length": 4.95,
   "inner_width": 2.1,
   "inner_height": 2.07,
   "gate_height": 1.96,
   "gate_width": 1.96,
   "cargo_volume": 21.5,
   "outer_auto_dimensions": "6.8 x 2.2 x 3.1 выс - 1 м",
   "pallets_or_trailer": "10 пал.\n(6+4)",
   "fixed_driver": "Багдасаров Арсен Рафикович",
   "group_name": "4м",
   "is_service": "false",
   "is_driver_exist": "true",
   "work_status": "work",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "м601рр 197",
   "marka": "Hyundai HD72",
   "load_capacity": 4,
   "inner_length": 5.02,
   "inner_width": 2.1,
   "inner_height": 2.16,
   "gate_height": 2.06,
   "gate_width": 2,
   "cargo_volume": 22.8,
   "outer_auto_dimensions": "7.1 x 2.12 x 3.3 выс - 1,04 м",
   "pallets_or_trailer": "10 пал.\n(6+4)",
   "comments": "гидроборт",
   "fixed_driver": "Рахманов Тилевалды Мурзахматович",
   "group_name": "5м",
   "is_service": "false",
   "is_driver_exist": "true",
   "work_status": "work",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "у682кт 799",
   "marka": "Mercedes-benz 816 Atego",
   "load_capacity": 5,
   "inner_length": 6.1,
   "inner_width": 2.48,
   "inner_height": 2.38,
   "gate_height": 2.33,
   "gate_width": 2.38,
   "cargo_volume": 36,
   "outer_auto_dimensions": "8.14 x 2.53  x 3.47 выс - 1 м",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,52 х 1,8  выс- 1м        ",
   "tires": "контин 215x75x17,5",
   "fixed_driver": "Кадыркулов Бактияр Кубанычпекович",
   "group_name": "6м",
   "is_service": "false",
   "is_driver_exist": "false",
   "work_status": "work",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "с238ув 99",
   "marka": "Mercedes-benz 814",
   "load_capacity": 5,
   "inner_length": 6.08,
   "inner_width": 2.47,
   "inner_height": 2.37,
   "gate_height": 2.24,
   "gate_width": 2.42,
   "cargo_volume": 35.6,
   "outer_auto_dimensions": "8 x 2.5 x 3.5",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,44 х 1,55",
   "tires": "Аелус 235x75x17,5",
   "group_name": "6м",
   "is_service": "false",
   "is_driver_exist": "false",
   "work_status": "work",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "в313ае 799",
   "marka": "Isuzu NQ",
   "load_capacity": 5,
   "inner_length": 6.2,
   "inner_width": 2.42,
   "inner_height": 2.41,
   "gate_height": 2.41,
   "cargo_volume": 36.2,
   "outer_auto_dimensions": "8.4x2.6x3.5",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,4 х 1,5",
   "tires": "мишлен 215x75x17,5 ",
   "fixed_driver": "Сагынов Нурадил Базарбаевич",
   "group_name": "6м",
   "is_service": "false",
   "is_driver_exist": "false",
   "work_status": "work",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "к562ер 799",
   "marka": "Isuzu NQ",
   "load_capacity": 5,
   "inner_length": 6.2,
   "inner_width": 2.45,
   "inner_height": 2.6,
   "gate_height": 2.56,
   "gate_width": 2.42,
   "cargo_volume": 39.5,
   "outer_auto_dimensions": "8.44 x 2.5 x 3.73 выс - 1,04 м ",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,55 х 2",
   "tires": "мишлен 215x75x17,5 ",
   "fixed_driver": "Абдурахманов Жоомарт Абдужопарович",
   "group_name": "6м",
   "is_service": "false",
   "is_driver_exist": "false",
   "work_status": "work",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "к327ер 799",
   "marka": "Isuzu NQ",
   "load_capacity": 5,
   "inner_length": 6.2,
   "inner_width": 2.45,
   "inner_height": 2.6,
   "gate_height": 2.56,
   "gate_width": 2.42,
   "cargo_volume": 39.5,
   "outer_auto_dimensions": "8.44 x 2,5 x 3.73  выс - 1.04 м",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,55 х 2",
   "tires": "мишлен 215x75x17,5 ",
   "fixed_driver": "Боруев Нурмухаммед Сабирбекович",
   "group_name": "6м",
   "is_service": "false",
   "is_driver_exist": "false",
   "work_status": "work",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т390ту 777",
   "marka": "Hino 300",
   "load_capacity": 5,
   "inner_length": 6.4,
   "inner_width": 2.45,
   "inner_height": 2.56,
   "gate_height": 2.5,
   "gate_width": 2.43,
   "cargo_volume": 40.1,
   "outer_auto_dimensions": "8.6 x … x 3.6 выс - 0,95 м",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,55 х 1,8",
   "tires": "екогамма 215x75x17,5",
   "fixed_driver": "Жигитали Уулу Азамат",
   "group_name": "6м",
   "is_service": "false",
   "is_driver_exist": "false",
   "work_status": "work",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т394ту 777",
   "marka": "Hino 300",
   "load_capacity": 5,
   "inner_length": 6.4,
   "inner_width": 2.45,
   "inner_height": 2.56,
   "gate_height": 2.51,
   "gate_width": 2.42,
   "cargo_volume": 40.1,
   "outer_auto_dimensions": "8.6 x … x 3.65   выс - 0,96 м",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,55 х 1,8",
   "tires": "екогамма 215x75x17,5",
   "fixed_driver": "Мергенов Жылдызбек Жакыпович",
   "group_name": "6м",
   "is_service": "false",
   "is_driver_exist": "false",
   "work_status": "work",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т396ту 777",
   "marka": "Hino 300",
   "load_capacity": 5,
   "inner_length": 6.4,
   "inner_width": 2.45,
   "inner_height": 2.56,
   "gate_height": 2.51,
   "gate_width": 2.42,
   "cargo_volume": 40.1,
   "outer_auto_dimensions": "8.6 x … x 3.65    выс - 0,96 м",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,55 х 1,8",
   "tires": "екогамма 215x75x17,5",
   "fixed_driver": "Абдуллажанов Бахтиер",
   "group_name": "6м",
   "is_service": "false",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т411ту 777",
   "marka": "Hino 300",
   "load_capacity": 5,
   "inner_length": 6.4,
   "inner_width": 2.45,
   "inner_height": 2.56,
   "gate_height": 2.51,
   "gate_width": 2.42,
   "cargo_volume": 40.1,
   "outer_auto_dimensions": "8.6 x … x 3.65  выс - 1,02 м",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,55 х 1,8",
   "tires": "екогамма 215x75x17,5",
   "fixed_driver": "Рахматов Эрмек Тимурович",
   "group_name": "6м",
   "is_service": "false",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т202рн 799",
   "marka": "Isuzu NQ",
   "load_capacity": 5,
   "inner_length": 6.2,
   "inner_width": 2.45,
   "inner_height": 2.6,
   "gate_height": 2.56,
   "gate_width": 2.42,
   "cargo_volume": 39.5,
   "outer_auto_dimensions": "8.44 x 2.5 x 3.73  выс - 0.95 м",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,55 х 2",
   "fixed_driver": "Марюшин Константин Сергеевич",
   "group_name": "6м",
   "is_service": "false",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т099рн 799",
   "marka": "Isuzu NQ",
   "load_capacity": 5,
   "inner_length": 6.2,
   "inner_width": 2.45,
   "inner_height": 2.6,
   "gate_height": 2.56,
   "gate_width": 2.42,
   "cargo_volume": 39.5,
   "outer_auto_dimensions": "8.44 x 2.5 x 3.73 выс - 0,96 м",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,55 х 2",
   "group_name": "6м",
   "is_service": "false",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т678рн 799",
   "marka": "Isuzu NQ",
   "load_capacity": 5,
   "inner_length": 6.2,
   "inner_width": 2.45,
   "inner_height": 2.6,
   "gate_height": 2.56,
   "gate_width": 2.42,
   "cargo_volume": 39.5,
   "outer_auto_dimensions": "8.44 x 2.5 x 3.73  выс - 0.94 м",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,55 х 2",
   "fixed_driver": "Тойчуев Максатбек Токтосунович",
   "group_name": "6м",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "е249са 799",
   "marka": "Isuzu NQ",
   "load_capacity": 5,
   "inner_length": 6.2,
   "inner_width": 2.45,
   "inner_height": 2.6,
   "gate_height": 2.56,
   "gate_width": 2.42,
   "cargo_volume": 39.5,
   "outer_auto_dimensions": "8.44 x 2.5 x 3.73",
   "pallets_or_trailer": "15 пал.\n(5+5+5)",
   "comments": "2,55 х 2",
   "fixed_driver": "Ханин Артём Ашотович",
   "group_name": "6м",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "у785кт 799",
   "marka": "Mercedes-benz 818 Atego",
   "load_capacity": 5,
   "inner_length": 7.21,
   "inner_width": 2.46,
   "inner_height": 2.3,
   "gate_height": 2.2,
   "gate_width": 2.42,
   "cargo_volume": 40.8,
   "outer_auto_dimensions": "9.18 x 2.53 x 3.42  выс - 1 м",
   "pallets_or_trailer": "18 пал.\n(6+6+6)",
   "comments": "2,52 х 1,9                   ",
   "tires": "блэклион 235x75x17,5",
   "fixed_driver": "Асриянц Авак Аликович",
   "group_name": "7м",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т578вн 199",
   "marka": "MAN LE 12.220",
   "load_capacity": 6,
   "inner_length": 7.23,
   "inner_width": 2.48,
   "inner_height": 2.38,
   "gate_height": 2.29,
   "gate_width": 2.42,
   "cargo_volume": 42.7,
   "outer_auto_dimensions": "9.26 x 2.5 x 3.61 выс - 1,12 м",
   "pallets_or_trailer": "18 пал.\n(6+6+6)",
   "comments": "2,52 х 1,8",
   "tires": "бриджст 265x70x17,5",
   "fixed_driver": "Жураев Бахтийор Баходирович",
   "group_name": "7м",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т579вн 199",
   "marka": "MAN LE 12.220",
   "load_capacity": 6,
   "inner_length": 7.28,
   "inner_width": 2.5,
   "inner_height": 2.53,
   "gate_height": 2.49,
   "gate_width": 2.43,
   "cargo_volume": 46,
   "outer_auto_dimensions": "9.33 x 2.52 x 3.67 выс - 1,04 м",
   "pallets_or_trailer": "18 пал.\n(6+6+6)",
   "comments": "2,52 х 1,8                     ",
   "tires": "контин  265x70x17,5",
   "fixed_driver": "Талалаев Сергей Борисович",
   "group_name": "7м",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т428ту 777",
   "marka": "Hino 500",
   "load_capacity": 6,
   "inner_length": 7.42,
   "inner_width": 2.44,
   "inner_height": 2.56,
   "gate_height": 2.51,
   "gate_width": 2.43,
   "cargo_volume": 46.3,
   "outer_auto_dimensions": "9,85 x … x 3.73  выс - 1,09 м",
   "pallets_or_trailer": "18 пал.\n(6+6+6)",
   "comments": "2,55 х 1,8",
   "tires": "бриджст 265x70x19,5",
   "fixed_driver": "Алибердиев Женишбек Ахматжанович",
   "group_name": "7м",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т442ту 777",
   "marka": "Hino 500",
   "load_capacity": 6,
   "inner_length": 7.42,
   "inner_width": 2.44,
   "inner_height": 2.56,
   "gate_height": 2.51,
   "gate_width": 2.43,
   "cargo_volume": 46.3,
   "outer_auto_dimensions": "9,85 x … x 3.73 выс - 1,09 м",
   "pallets_or_trailer": "18 пал.\n(6+6+6)",
   "comments": "2,56 х 1,8",
   "tires": "бриджст 265x70x19,5",
   "fixed_driver": "Хужакулов Ашурали Рахманович",
   "group_name": "7м",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "к849от 777",
   "marka": "Hino 500",
   "load_capacity": 6,
   "inner_length": 7.42,
   "inner_width": 2.44,
   "inner_height": 2.56,
   "gate_height": 2.51,
   "gate_width": 2.43,
   "cargo_volume": 46.3,
   "outer_auto_dimensions": "9,85 x … x 3.73 выс - 1,07 м",
   "pallets_or_trailer": "18 пал.\n(6+6+6)",
   "comments": "2,56 х 1,8",
   "tires": "бриджст 265x70x19,5",
   "fixed_driver": "Кадыров Абдурашит Ганиевич",
   "group_name": "7м",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "к816ер 799",
   "marka": "Isuzu FS",
   "load_capacity": 6,
   "inner_length": 7.4,
   "inner_width": 2.44,
   "inner_height": 2.61,
   "gate_height": 2.57,
   "gate_width": 2.41,
   "cargo_volume": 47.1,
   "outer_auto_dimensions": "9.94 x 2.55 x 3.75",
   "pallets_or_trailer": "18 пал.\n(6+6+6)",
   "comments": "2,55 х 2  выс - 1,02 м",
   "tires": "мишлен 245x70x19,5",
   "fixed_driver": "Абдрапиев Султанали Алибаевич",
   "group_name": "7м",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "к789ер 799",
   "marka": "Isuzu FS",
   "load_capacity": 6,
   "inner_length": 7.4,
   "inner_width": 2.44,
   "inner_height": 2.61,
   "gate_height": 2.57,
   "gate_width": 2.41,
   "cargo_volume": 47.1,
   "outer_auto_dimensions": "9.94 x 2.55 x 3.75 выс - 1,05 м",
   "pallets_or_trailer": "18 пал.\n(6+6+6)",
   "comments": "2,55 х 2\nрохла",
   "tires": "мишлен 245x70x19,5",
   "fixed_driver": "Айрапетов Антон Александрович",
   "group_name": "7м",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "к249нр 799",
   "marka": "Mercedes-Benz Atego 1222",
   "load_capacity": 6,
   "inner_length": 7.24,
   "inner_width": 2.45,
   "inner_height": 2.66,
   "gate_height": 2.63,
   "gate_width": 2.41,
   "cargo_volume": 47.2,
   "outer_auto_dimensions": "9,26 x 2,53 x 3,86   выс - 1,08 м",
   "pallets_or_trailer": "18 пал.\n(6+6+6)",
   "comments": "2,51 х 1,8",
   "tires": "континент 265x70x19,5",
   "fixed_driver": "Очилов Алишер Файзуллоевич",
   "group_name": "7м",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "н403ок 799",
   "marka": "Isuzu FS",
   "load_capacity": 6,
   "inner_length": 7.4,
   "inner_width": 2.44,
   "inner_height": 2.6,
   "gate_height": 2.57,
   "gate_width": 2.42,
   "cargo_volume": 46.9,
   "outer_auto_dimensions": "9,93 x 2,5 x 3,77  выс - 1.05 м",
   "pallets_or_trailer": "18 пал.\n(6+6+6)",
   "comments": "2.55 х 2",
   "fixed_driver": "Лутцев Алексей Евгеньевич",
   "group_name": "7м",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "е135кн 77",
   "marka": "Renault Premium",
   "load_capacity": 20,
   "fixed_driver": "Абдуллаев Кахрамон Анваржанович",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "м464хо 199",
   "marka": "Renault Premium 450 DXI ",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.5,
   "inner_height": 2.9,
   "gate_height": 3,
   "gate_width": 2.5,
   "cargo_volume": 98.6,
   "outer_auto_dimensions": "3,55x4-4",
   "pallets_or_trailer": "вс2202 77",
   "fixed_driver": "Исахужаев Кахрамонжон Рустамбекович",
   "fixed_trailer": "вс2202 77",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "м474хо 199",
   "marka": "Renault Premium 450 DXI ",
   "load_capacity": 20,
   "fixed_driver": "Турсунов Данияр Тургунбаевич",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "о639со 777",
   "marka": "Renault Premium",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.5,
   "inner_height": 2.75,
   "gate_height": 2.72,
   "gate_width": 2.48,
   "cargo_volume": 93.5,
   "outer_auto_dimensions": "3,9x4,02-4",
   "pallets_or_trailer": "еа1783 77",
   "fixed_driver": "Гаибов Шакир Камилжанович",
   "fixed_trailer": "еа1783 77",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "в645рн 197",
   "marka": "Renault Premium",
   "load_capacity": 20,
   "fixed_driver": "Юлдашев Исломбек",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "в646рн 197",
   "marka": "Renault Premium",
   "load_capacity": 20,
   "fixed_driver": "Рахмонов Эркинбой Абдурайимович",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "в647рн 197",
   "marka": "Renault Premium",
   "load_capacity": 20,
   "fixed_driver": "Абдуманнапов Абдурасул Абдугапар Уулу",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "е741уе 77",
   "marka": "Renault Premium",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.48,
   "inner_height": 2.8,
   "gate_height": 2.61,
   "gate_width": 2.49,
   "cargo_volume": 94.4,
   "pallets_or_trailer": "ек5952 50",
   "fixed_driver": "Хакимов Расулжон Рабилжанович",
   "fixed_trailer": "ек5952 50",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "е742уе 77",
   "marka": "Renault Premium",
   "load_capacity": 20,
   "inner_length": 13.6,
   "fixed_driver": "Дехканов Ибрагимжон Исраилович",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "в152ае 799",
   "marka": "DAF XF460",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.48,
   "inner_height": 2.71,
   "gate_height": 2.71,
   "gate_width": 2.48,
   "cargo_volume": 91.4,
   "outer_auto_dimensions": "3,55x4-4",
   "pallets_or_trailer": "еа6555 77",
   "fixed_driver": "Кахаров Хусанджон",
   "fixed_trailer": "еа6555 77",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "в262ае 799",
   "marka": "DAF XF460",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.5,
   "inner_height": 2.75,
   "gate_height": 2.58,
   "gate_width": 2.48,
   "cargo_volume": 93.5,
   "outer_auto_dimensions": "3,85x4-3,9",
   "pallets_or_trailer": "ек4389 50",
   "fixed_driver": "Гаибов Баходир Камилжанович",
   "fixed_trailer": "ек4389 50",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т211рн 799",
   "marka": "Renault T 4x2",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.5,
   "inner_height": 2.9,
   "gate_height": 2.92,
   "gate_width": 2.5,
   "cargo_volume": 98.6,
   "outer_auto_dimensions": "3,93x4,05-4,05",
   "pallets_or_trailer": "вс2201 77",
   "fixed_driver": "Абдуллажанов Дастанбек Шавкатович",
   "fixed_trailer": "вс2201 77",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "к818нр 799",
   "marka": "Renault T 4x2",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.48,
   "inner_height": 2.7,
   "cargo_volume": 91.1,
   "outer_auto_dimensions": "3,92x3,95-4",
   "pallets_or_trailer": "ек0017 77",
   "fixed_driver": "Карабаев Валижан Ганижанович",
   "fixed_trailer": "ек0017 77",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "к876нр 799",
   "marka": "Renault T 4x2",
   "load_capacity": 20,
   "inner_length": 13.6,
   "pallets_or_trailer": "ен6862 50",
   "fixed_driver": "Абдугапар Уулу Элдарбек",
   "fixed_trailer": "ен6862 50",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "к895нр 799",
   "marka": "Renault T 4x2",
   "load_capacity": 20,
   "inner_length": 13.6,
   "pallets_or_trailer": "ен6861 50",
   "fixed_driver": "Жураев Шухраджон Туйчибаевич",
   "fixed_trailer": "ен6861 50",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т617рн 799",
   "marka": "Renault T 4x2",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.5,
   "inner_height": 2.87,
   "cargo_volume": 97.6,
   "outer_auto_dimensions": "3,9x4,05-4,05",
   "pallets_or_trailer": "ву9544 77",
   "fixed_driver": "Тажибаев Анвар Хамотханович",
   "fixed_trailer": "ву9544 77",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "т632рн 799",
   "marka": "Renault T 4x2",
   "load_capacity": 20,
   "inner_length": 13.6,
   "fixed_driver": "Абдуллаев Анваржон Бурханович",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "р123хт 799",
   "marka": "Renault T 4x2",
   "load_capacity": 20,
   "inner_length": 13.6,
   "pallets_or_trailer": "уу8469 77",
   "fixed_driver": "Салиев Махмуджан Сабирович",
   "fixed_trailer": "уу8469 77",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "р986хм 799",
   "marka": "Renault T 4x2",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.48,
   "inner_height": 2.78,
   "cargo_volume": 93.8,
   "pallets_or_trailer": "уу8471 77",
   "fixed_driver": "Абидов Рустамбек Уктамович",
   "fixed_trailer": "уу8471 77",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "р433хт 799",
   "marka": "Renault T 4x2",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.48,
   "inner_height": 2.72,
   "cargo_volume": 91.7,
   "pallets_or_trailer": "уу1462 77",
   "fixed_driver": "Гаибов Анваржан Камилжанович",
   "fixed_trailer": "уу1462 77",
   "group_name": "тягачи",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "в358ае 799",
   "marka": "Isuzu NQ",
   "load_capacity": "20 фт.",
   "outer_auto_dimensions": "8.23 x 2.5 x 3.65",
   "group_name": "Современник isuzu",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "в365ае 799",
   "marka": "Isuzu NQ",
   "load_capacity": "20 фт.",
   "outer_auto_dimensions": "8.23 x 2.5 x 3.65",
   "fixed_driver": "Урозбоев Акилбек Каримжон Угли",
   "group_name": "Современник isuzu",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "в405ае 799",
   "marka": "Isuzu NQ",
   "load_capacity": "20 фт.",
   "outer_auto_dimensions": "8.23 x 2.5 x 3.65",
   "fixed_driver": "Гаибов Мухиддин Баходирович",
   "group_name": "Современник isuzu",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "к108ер 799",
   "marka": "Isuzu NQ",
   "load_capacity": "20 фт.",
   "outer_auto_dimensions": "8.23 x 2.5 x 3.65",
   "fixed_driver": "Алиев Куат Алламжарович",
   "group_name": "Современник isuzu",
   "is_service": "true",
   "is_driver_exist": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "вс2202 77",
   "marka": "Прицеп",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.5,
   "inner_height": 2.9,
   "gate_height": 3,
   "gate_width": 2.5,
   "cargo_volume": 98.6,
   "outer_auto_dimensions": "3,55x4-4",
   "fixed_trailer": "м464хо 199",
   "group_name": "Прицеп",
   "is_service": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "еа1783 77",
   "marka": "Прицеп",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.5,
   "inner_height": 2.75,
   "gate_height": 2.72,
   "gate_width": 2.48,
   "cargo_volume": 93.5,
   "outer_auto_dimensions": "3,9x4,02-4",
   "fixed_trailer": "о639со 777",
   "group_name": "Прицеп",
   "is_service": "false",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "ек5952 50",
   "marka": "Прицеп",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.48,
   "inner_height": 2.8,
   "gate_height": 2.61,
   "gate_width": 2.49,
   "cargo_volume": 94.4,
   "fixed_trailer": "е741уе 77",
   "group_name": "Прицеп",
   "is_service": "false",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "еа6555 77",
   "marka": "Прицеп",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.48,
   "inner_height": 2.71,
   "gate_height": 2.71,
   "gate_width": 2.48,
   "cargo_volume": 91.4,
   "outer_auto_dimensions": "3,55x4-4",
   "fixed_trailer": "в152ае 799",
   "group_name": "Прицеп",
   "is_service": "false",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "ек4389 50",
   "marka": "Прицеп",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.5,
   "inner_height": 2.75,
   "gate_height": 2.58,
   "gate_width": 2.48,
   "cargo_volume": 93.5,
   "outer_auto_dimensions": "3,85x4-3,9",
   "fixed_trailer": "в262ае 799",
   "group_name": "Прицеп",
   "is_service": "false",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "вс2201 77",
   "marka": "Прицеп",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.5,
   "inner_height": 2.9,
   "gate_height": 2.92,
   "gate_width": 2.5,
   "cargo_volume": 98.6,
   "outer_auto_dimensions": "3,93x4,05-4,05",
   "fixed_trailer": "т211рн 799",
   "group_name": "Прицеп",
   "is_service": "false",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "ек0017 77",
   "marka": "Прицеп",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.48,
   "inner_height": 2.7,
   "cargo_volume": 91.1,
   "outer_auto_dimensions": "3,92x3,95-4",
   "fixed_trailer": "к818нр 799",
   "group_name": "Прицеп",
   "is_service": "false",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "ву9544 77",
   "marka": "Прицеп",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.5,
   "inner_height": 2.87,
   "cargo_volume": 97.6,
   "outer_auto_dimensions": "3,9x4,05-4,05",
   "fixed_trailer": "т617рн 799",
   "group_name": "Прицеп",
   "is_service": "false",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "уу8471 77",
   "marka": "Прицеп",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.48,
   "inner_height": 2.78,
   "cargo_volume": 93.8,
   "fixed_trailer": "р986хм 799",
   "group_name": "Прицеп",
   "is_service": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  },
  {
   "gos_number": "уу1462 77",
   "marka": "Прицеп",
   "load_capacity": 20,
   "inner_length": 13.6,
   "inner_width": 2.48,
   "inner_height": 2.72,
   "cargo_volume": 91.7,
   "fixed_trailer": "р433хт 799",
   "group_name": "Прицеп",
   "is_service": "true",
   "work_status": "free",
   "current_order": "null",
   "foto_auto": "xxx",
   "foto_pts": "xxx",
   "foto_sts": "xxx",
   "foto_osago": "xx",
   "osago_number": "x",
   "osago_start": "x",
   "osago_end": "x"
  }
 ]